server:
  port: 8888


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/e5renew
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

# springdoc-openapi????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.lhq.e5renew.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn
